name: FRONTEND CI
on:
  push:
    branches: ["main"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      - name: version
        value: 1.1.1
    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: "PANTS-GOORM/infra"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: manifest

      - name: Update Deployment image tag
        run: |
          sed -i "s|chickennight/pants-fe:[^[:space:]]*|chickennight/pants-fe:${{ env.version }}" ./manifest/test.yaml
          cd manifest
          git config user.name "chickennight"
          git config user.email "john0513@naver.com"
          git add test.yaml
          git commit -m "Update image tag to ${{ env.version }}"
          git push
